### PR TITLE
VAN-4188 applied special chars handling filter to app-modules

### PR DESCRIPTION
**Pull request by cc-shekher**

### CODE REVIEW

**Comment by rajatsharma111** [comment]
@cc-shekher I was testing this change in local setup and getting this error-

Payload-

```
{
  "appId": "de1451f4-8f23-43b4-b98a-6d7499f37f0a",
  "name": "cldcvr/codepipes-tutorials-integration-pipeline-1",
  "orgId": "8896dbd7-1bb2-443d-bd88-f3281bff3e19",
  "projId": "3c2eb9ce-7882-4551-85e8-8ce9f0ba19f3",
  "inputAppArtifact": {
    "id": "5c67cf6c-24d6-4415-aa37-50dcd1713c14"
  },
  "config": {
    "vars": {
      
    },
    "sensitive": {
      
    }
  },
  "pipeline": [
    {
      "moduleRefId": "azure:dotnet-build@1",
      "inputs": {
        "pool_name": ""
      }
    },
    {
      "moduleRefId": "azure:publish-artifact@1",
      "inputs": {
        "feed_name": "$(CPI__artifact_feed)",
        "pool_name": ""
      }
    }
  ]
}
```

Response-
```
{
    "Code": "IntegrationPipelineConfigErr",
    "Kind": 422,
    "Message": "Invalid App Integration pipeline configuration for azure:dotnet-build@1",
    "payload": {
        "moduleRefId": "azure:dotnet-build@1"
    },
    "Nested": {
        "Code": "UtilsUnexpectedError",
        "Kind": 500,
        "Message": "azure renderer: malformed template in module 'azure:dotnet-build@1': [Error (where: filter:cpi_replacespecial) | Line 1 Col 41 near 'cpi_replacespecial'] invalid input"
    }
}
```

**Comment by rajatsharma111** [comment]
@cc-shekher I was trying to test the after the fix but seems now its failing with this reason-

https://dev.azure.com/cldcvrdevusa/Codepipes-QA/_build/results?buildId=82679&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=91b01b5a-269c-561e-3792-ed889edcc254

```

Publishing package: clls[^a-zA-Z0-9-]+8b790a7e-66481ab841ee70d27f47437b25e87b338e7fb0ef.zip, version: 0.1.0 using feed id: 73cc8f46-22ab-7c5b-a4a9-5a61facf14ae, project: null

{"@t":"2023-06-09T12:11:38.6346660Z","@m":"The package name provided is invalid. Universal package names must be one or more lowercase alphanumeric segments separated by a dash, dot or underscore. The package name must be under 256 characters.","@i":"69c271d4","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2023-06-09 12:11:38.634Z"}

```

**Comment by cc-shekher** [comment]
> @cc-shekher I was trying to test the after the fix but seems now its failing with this reason-
> 
> https://dev.azure.com/cldcvrdevusa/Codepipes-QA/_build/results?buildId=82679&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=91b01b5a-269c-561e-3792-ed889edcc254
> 
> ```
> 
> Publishing package: clls[^a-zA-Z0-9-]+8b790a7e-66481ab841ee70d27f47437b25e87b338e7fb0ef.zip, version: 0.1.0 using feed id: 73cc8f46-22ab-7c5b-a4a9-5a61facf14ae, project: null
> 
> {"@t":"2023-06-09T12:11:38.6346660Z","@m":"The package name provided is invalid. Universal package names must be one or more lowercase alphanumeric segments separated by a dash, dot or underscore. The package name must be under 256 characters.","@i":"69c271d4","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2023-06-09 12:11:38.634Z"}
> ```

There was an issue with the nomenclature which was fixed as part of [VAN-4157](https://cldcvr.atlassian.net/browse/VAN-4157). The fix has been deployed on staging.

**Comment by rajatsharma111** [comment]
@cc-shekher I have tested the azure dot-net-build and publish artifact module locally so we are good to merge this now.

**Comment by cc-shekher** [comment]
> @cc-shekher I have tested the azure dot-net-build and publish artifact module locally so we are good to merge this now.

Thanks @rajatsharma111 Can you please add review to the PR.

**Review by kanaksinghal — APPROVED** [review]

**Pull request merged**
